### PR TITLE
Modularize and expand qa_package()

### LINKED ISSUE #159: Modularize qa_package
Split `qa_package` checks into those that directly download data files and those that don't.  I think this entails putting some of `qa_attributes` into a function that checks the actual data files.

### PR DESCRIPTION
**Pull request by drkrynstrng**
This update for the QA functions has multiple dimensions.

First, I modularized the existing `qa_package()` function by creating separate helper functions to download and read data objects. This closes #159. For checking the congruence of data and metadata attributes, the primary purpose of the existing `qa_package()`, I renamed the function to `qa_congruence()`. I also changed the output messages to be returned in a list.

Second, I redefined `qa_package()` to include all types of QA checks, including checks for EML metadata based on the MetaDIG checks as well as checks for system metadata (effectively a wrapper around `qa_eml()` and `qa_sysmeta()`). The default is set to return only results with a FAILURE or ERROR status. As part of this, `qa_congruence()` is included as an option, with the default set to not run for load/speed reasons.

The general intended use when processing data packages is `qa_package(mn, rm_pid)` or with congruence checks `qa_package(mn, rm_pid, congruence = TRUE)`. When checking an EML object in R before or after making edits, then the intended use is `qa_eml(eml)`. For prettier output I also included `qa_view()`, a convenience function that uses the listviewer package to output results. Using `qa_view(qa_package(mn, rm_pid))` is a better way to see the results in the viewer in RStudio.

Third, these updates are meant to feedback into the relevant MetaDIG quality suites. As part of this, we would need to identify which checks we want to add and then classify these new checks into Identification, Discovery, Interpretation, or Informational (which do not impact quality scores). The potential additions are QA checks for the physical, congruence of data and metadata attributes, and data object duplication. All of these additions seem to be Informational checks. I think the QA checks for system metadata would be excluded from MetaDIG, but correct me if I'm wrong. We could potentially expand these checks too.

I did a lot of debugging with these functions already and there are probably more bugs, but we can fix them as we find them. I also need to add more unit tests. Let me know if you have suggestions for improvements in the code, in the organization of the code or output, or in output messages.

### CODE REVIEW

**Comment by drkrynstrng** [comment]
@jagoldstein @jeanetteclark @dmullen17 These are my proposed changes to the `qa_package()` function. I recommend testing it out on a few packages to see how it differs.

We should also develop formal xml files for the quality checks we want to add to the existing quality suite using the metadig package, but that would be separate. There would be some duplication doing that but it also provides some flexibility.

**Comment by jeanetteclark** [comment]
Hey Derek this looks good and I think the modularization makes sense, I'd like to test it out though. Do we have a wrapper as well? Or are we deliberately staying away from that

**Comment by drkrynstrng** [comment]
What do you mean by wrapper in this case? I redefined `qa_package()` here to be the main wrapper around the newer functions `qa_eml()`, `qa_congruence()`, and `qa_sysmeta()`, which could all be used separately.

**Comment by jeanetteclark** [comment]
ah gotcha - sorry I didn't see the commit to qa_package. Yeah, I think this is fine to merge especially because I want to test!

**Comment by jagoldstein** [comment]
@drkrynstrng it would be helpful to build out some of the error messages to be more informative/ explanatory.

e.g.:
```
Error in value[[3L]](cond) : 
Failed to read file https://cn.dataone.org/cn/v2/resolve/
```
It would be great for the output to give feedback on 'Why it failed' (for example).

**Comment by drkrynstrng** [comment]
Yeah, there's definitely room for improvement in the messages. I'll go back and expand those, especially the 'why' parts.

**Pull request merged**
